name = "api-dev"
type = "webpack"
account_id = "fbcf66bdf52427e2e6abbf4dcbd3c6fe"
workers_dev = true
route = ""
zone_id = ""
vars = { ENVIRONMENT = "dev", UTIL_API_ENDPOINT = "https://dawn-tqa-staging.begin.app" }

[env.staging]
name = "api-staging"
vars = { ENVIRONMENT = "staging" }


[env.production]
name = "api"
vars = { ENVIRONMENT = "production" }